# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73768eef565ef9abeb566014ef2dd7918ac83985de8e9c8a18d45994e932de48c632a08bb79ec0744cfbb433337f2517ee36ac90026f9ca15616ad1e6f1678c7

test:
  secret_key_base: 148a0b99cc726d080bc9b6ed8170532849ea3923fcbc8a747fcf5a623c76d4bb0d50bba5a377e52d366b386977e9a074cebaeb170ffdf5d2777dd4ecf3175bc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
